### ISSUE TITLE
Request doesn't run: execution expired

### ISSUE THREAD

**Issue by sashazykov** [romanbsd/livejournal#3]
Gem has stopped to work. Now I am getting this error:

```
/rubies/ruby-1.8.7-p352/lib/ruby/1.8/timeout.rb:64:in `rbuf_fill': execution expired (Timeout::Error)
    from /rubies/ruby-1.8.7-p352/lib/ruby/1.8/net/protocol.rb:134:in `rbuf_fill'
    from /rubies/ruby-1.8.7-p352/lib/ruby/1.8/net/protocol.rb:116:in `readuntil'
    from /rubies/ruby-1.8.7-p352/lib/ruby/1.8/net/protocol.rb:126:in `readline'
    from /rubies/ruby-1.8.7-p352/lib/ruby/1.8/net/http.rb:2028:in `read_status_line'
    from /rubies/ruby-1.8.7-p352/lib/ruby/1.8/net/http.rb:2017:in `read_new'
    from /rubies/ruby-1.8.7-p352/lib/ruby/1.8/net/http.rb:1051:in `request'
    from /rubies/ruby-1.8.7-p352/lib/ruby/1.8/net/http.rb:1037:in `request'
    from /rubies/ruby-1.8.7-p352/lib/ruby/1.8/net/http.rb:543:in `start'
    from /rubies/ruby-1.8.7-p352/lib/ruby/1.8/net/http.rb:1035:in `request'
    from /rubies/ruby-1.8.7-p352/lib/ruby/1.8/net/http.rb:845:in `post'
    from /gems/ruby-1.8.7-p352/gems/livejournal-0.3.4/lib/livejournal/request.rb:91:in `run'
    from /gems/ruby-1.8.7-p352/gems/livejournal-0.3.4/lib/livejournal/request.rb:132:in `run'
    from /gems/ruby-1.8.7-p352/gems/livejournal-0.3.4/lib/livejournal/request.rb:66:in `initialize'
    from /gems/ruby-1.8.7-p352/gems/livejournal-0.3.4/lib/livejournal/login.rb:31:in `initialize'
```

**Comment by romanbsd** [comment]
It's probably a problem with your internet provider, proxy, or LJ throttling of your requests. Works fine here.

**Comment by sashazykov** [comment]
It doesn't work on my server too. Simplest test fails:

```
require 'rubygems'
require 'livejournal'

user = LiveJournal::User.new('test', 'test')
login = LiveJournal::Request::Login.new(user)
login.run
```

**Comment by sashazykov** [comment]
I have tested it on my second server. timeout again(

**Comment by romanbsd** [comment]
I didn't say that the failure is fictional. I just said that it's not due to a problem with the gem.

**Comment by sashazykov** [comment]
Is it possible to increase timeout?

**Comment by romanbsd** [comment]
The default, if I'm not mistaken, is 60 seconds. If you'd like to increase it, then you can monkey patch the LiveJournal::Request::Req#run and add

```
h.read_timeout = X
```
